### ISSUE TITLE
How would you make scented mouse pads?

### ISSUE THREAD

**Issue by sindresorhus** [stephenplusplus/ama#10]

**Comment by stephenplusplus** [comment]
This is something I think about a lot, and I don't have the answer yet, sadly. Ideas welcome.

**Comment by stephenplusplus** [comment]
I've given it a few days, and I had an idea. The question is what can you find that is scented and works as a mouse pad? That left me in a sleepless rut, then it hit me: what better plane than the earth that surrounds us? I took my laptop and wireless mouse outside to the smell of freshly-cut grass, and voila! It didn't really work.

@#&$ this question. It's not possible.

(But thanks for asking :))
