### ISSUE TITLE
How much time did you spend developing your iOS app `youmeyou`?

### ISSUE THREAD

**Issue by sindresorhus** [stephenplusplus/ama#12]
http://www.youmeyou.us/

**Comment by stephenplusplus** [comment]
Soooo much. Early days, long nights. Didn't keep track of it really, but a lot. I learned a whole lot in the process. The idea started years ago, but real development started November 2014. I built the first app with Ionic/Angular, and released version 1.0 in late January. Version 2 was also Ionic, then I redid it in React Native, which is now in the app store as 3.0.

Along the way, I had to learn new things, get up to speed on some CSS skills/JS perf considerations I didn't have to worry about before, and write many new services to support the app (push notification server, image decoding, limiting stale notifications, email routines, creating archives for downloadable content, and much more). Not to mention trying to market the thing, which included many campaigns just about everywhere I could run them, videos, screenshots, website, blog posts, twitter/facebook posts, etc. I know you've had to do this stuff, too-- it's exhausting and fun at the same time.

I'm still waiting on a rush of users to join the app, but if that day doesn't come, I still learned a lot from the experience.

**Comment by sindresorhus** [comment]
:+1:
