### ISSUE TITLE
What's your dev environment?

### ISSUE THREAD

**Issue by drKraken** [stephenplusplus/ama#13]

**Comment by stephenplusplus** [comment]
- [Sublime Text 3](http://www.sublimetext.com/3) - [github theme](https://github.com/sethlopezme/InspiredGitHub.tmtheme)
- [Spotify](https://www.spotify.com)
- [iTerm 2](https://www.iterm2.com) - [dracula theme](https://github.com/zenorocha/dracula-theme)
- [nvm](https://github.com/creationix/nvm)
- [spectacle](http://spectacleapp.com)
