### ISSUE TITLE
Вы понимаете что тут написано?

### ISSUE THREAD

**Issue by drKraken** [stephenplusplus/ama#15]
Do you know Russian? Have you ever been there or plan to visit it? :smile:

**Comment by ivarprudnikov** [comment]
Just to eliminate thoughts that it might be some sort of trolling, issue title translation is: "Do you understand what is written here?"

**Comment by stephenplusplus** [comment]
My paternal grandparents were born and raised in the Ukraine, so some of those characters look familiar, but no, sadly-- I needed @ivarprudnikov's help!

It would be cool to visit someday, but no plans in the near future. I've got two little punks living in my house that demand we stay domestic for the next several years. But to be fair, I still have a lot of discovering my own country left to do.

Thanks for the question... and the translation :)
