### ISSUE TITLE
If you could no longer write JavaScript, which language would you use?

### ISSUE THREAD

**Issue by passy** [stephenplusplus/ama#18]
Don't know a good reason, but let's just imagine you had something like lactose intolerance but when touching JavaScript.

**Comment by stephenplusplus** [comment]
Magnificent, jaw-dropping, mind-melting, fantastically-penned question! :)

JavaScript intolerance affects over 6/10 Americans every year. I'd hate to be just another statistic, but if I did develop such an affliction, you would probably find me buried in Objecive-C and Swift StackOverflow tabs. I'm kind of a poser-coder, cause I only got into this to make stuff I want to use. Making iOS apps is fun for me, cause the platform (as a consumer and a developer) *just works* for my tastes (as a consumer and a developer). If it's too much torture, then I'll just go outside.

**Comment by sindresorhus** [comment]
There are pills for lactose intolerance now.

**Comment by stephenplusplus** [comment]
I'm lactose intolerance pills intolerant.

**Comment by passy** [comment]
Someone youmeyou that ^

Unfortunately, I do not have one of those just-works devices at my disposal right now.
