### ISSUE TITLE
Selfie

### ISSUE THREAD

**Issue by passy** [stephenplusplus/ama#19]
See sindresorhus/ama#75.

**Comment by arthurvr** [comment]
+1 :lollipop:

**Comment by stephenplusplus** [comment]
@:)

**Comment by passy** [comment]
CHEATERRRR

**Comment by stephenplusplus** [comment]
![image](https://cloud.githubusercontent.com/assets/723048/8533956/69b61a50-2406-11e5-9ec5-d108365376fd.jpg)

**Comment by stephenplusplus** [comment]
I'm most productive sideways.
