### ISSUE TITLE
How's your experience with React Native been so far?

### ISSUE THREAD

**Issue by passy** [stephenplusplus/ama#24]

**Comment by stephenplusplus** [comment]
This was my first real experience with React, and I totally love it. It reminded me a bit of Backbone, which I used to like quite a bit. The lifecycle architecture is great and fits neatly with Obj-C iOS apps. For the next app, I'll try to follow more closely with the React/Flux principles. For this one ([youmeyou](http://www.youmeyou.us)), I just wanted to get something out there.

The transition from Ionic was very welcome. While I do love the professionalism of the Ionic team and camaraderie of the community, it just couldn't match the true native experience. (I can see myself looking at this years in the future and saying "what even *was* 'the native experience,' and why did I *have* to have it?)

People say once you get a tattoo, you're hooked. I didn't experience that for my tattoo, but I did for putting apps on the App Store: now that I've made one, I can't stop having ideas for others. It's likely I make a return sometime before next year, and when I do, I'm excited to see how much React Native has improved in the difference.
