### ISSUE TITLE
what programming language would you suggest?

### ISSUE THREAD

**Issue by robbbz** [stephenplusplus/ama#25]
I am a javascript developer programming node and browser-side. Except PHP I don't know any other back-end languages. I want to learn something that I can use for web applications, but also just for other kind of programming. What language would you suggest me to use?

**Comment by stephenplusplus** [comment]
Wow, it's been a year! Have you learned any new languages? I'll ask the same question back to you; now that you've been someone who didn't know which way to go, how would you advise yourself from a year ago?
