### ISSUE TITLE
Where do you currently work and what do you do?

### ISSUE THREAD

**Issue by sindresorhus** [stephenplusplus/ama#26]

**Comment by stephenplusplus** [comment]
I'm kind of a loose cannon right now. I'm working with Google Cloud Platform on the [gcloud-node](https://github.com/googlecloudplatform/gcloud-node) right now, but who knows where I'll go next.

Maybe we can finally start taptapship and make billions? :)

**Comment by sindresorhus** [comment]
Sorry dude, I'm starting a street food stall in Bangkok selling glazed carrots.

// @passy

**Comment by stephenplusplus** [comment]
You guys would probably benefit from a street musician then, which I happen to not be. But I do know how to play guitar-- I even have one. I'll bring it, sing songs about glaze and carrots, and we will harmonize our way to billions!

**Comment by passy** [comment]
You seem to be lacking all the skills a successful street musician should
have. Welcome on board!
