### ISSUE TITLE
Any thoughts on functional programming?

### ISSUE THREAD

**Issue by nmehta6** [stephenplusplus/ama#28]
Do you prefer any functional programming languages/libraries?

Do you have any thoughts on [LiveScript](http://livescript.net) or [ramdajs](http://ramdajs.com/0.16/index.html)?

**Comment by stephenplusplus** [comment]
I think I'm interested in functional programming, but I'm also not.

Only at the beginning of a new adventure or by necessity, do I want to spend time learning something that works differently than what my mind is used to. I consider those challenges a wise investment, but I treat it as such; there are risks and the time has to be right.

Right now, my short-term goals don't involve pushing myself in that direction. Eventually, I'll start the cycle again where my mind gets bored, or I've reached a comfort level with the parameters I work within, and I'll try to feed it something new. Some functional language is likely where I'll go, mainly so I can fit in with @passy.

Thanks for the question. Sorry I took so long to answer.
