### ISSUE TITLE
What is a taptapship?

### ISSUE THREAD

**Issue by arthurvr** [stephenplusplus/ama#30]

**Comment by stephenplusplus** [comment]
taptapship started long ago as a repo: https://github.com/stephenplusplus/taptapship/wiki/tap-tap-huh%3F

Generally put, the idea was to make learning web technologies easier. So easy, you just tap, tap, then ship your product.

I made that repository, then added some folks as owners to get their attention (I realize that's poor form now, so a delayed sorry!). Everyone was pretty cool about it though, and it lead to [a good discussion](https://github.com/stephenplusplus/taptapship/issues/1) on how confusing everything was at the time (... and still is).

Ultimately, I never made the site. Other priorities emerged (family/work/todomvc/yeoman), and I just let it stand.

taptapship took on a new form when my friend Dave and I were thinking of starting a local design shop: http://stephenplusplus.github.io/taptap/#/

Now, it's just my organization on GitHub that I put mutually interesting projects in: https://github.com/taptapship
