### ISSUE TITLE
Up to much this weekend?

### ISSUE THREAD

**Issue by passy** [stephenplusplus/ama#35]
![](http://www.cherryplucker.com/wp-content/uploads/2013/06/rebecca-black-friday-3.gif)

**Comment by passy** [comment]
Weekend task for me:

[ ] Clean my keyboard.

**Comment by stephenplusplus** [comment]
Oh, just doing some family stuff. Baby P turns 3 in a month, so we're going to a play place to see about hosting her birthday party there. Then later, we're going to find some scenic nature spots to take pictures of baby B who turned 6 months last week. It will be a nice break from the flashing cursors that stare at me all week.

Thanks for asking! I'll keep this open until your weekend is resolved.
