### ISSUE TITLE
What's your guiltiest pleasure?

### ISSUE THREAD

**Issue by silvenon** [stephenplusplus/ama#38]

**Comment by stephenplusplus** [comment]
Music movies.

![](https://images-na.ssl-images-amazon.com/images/I/51VWPBB9VRL.jpg)
https://en.wikipedia.org/wiki/Eddie_and_the_Cruisers

![](http://ia.media-imdb.com/images/M/MV5BMTczMzM2MTM0NF5BMl5BanBnXkFtZTcwMTIwMDQ0MQ@@._V1_.jpg)
http://www.imdb.com/title/tt0117887/
