### ISSUE TITLE
When are you coming to London?

### ISSUE THREAD

**Issue by sindresorhus** [stephenplusplus/ama#4]
Related: https://github.com/sindresorhus/ama/issues/4

**Comment by stephenplusplus** [comment]
Oh my gosh, I would love to. Really. When Jess and I can take a long vacation (right now, we're lucky to have 2 hours due to the babies needing us).

**Comment by addyosmani** [comment]
I'm hearing Jess + babies travelling! :D

**Comment by stephenplusplus** [comment]
I think our older one could handle it, so maybe in a couple years the young one can. We would seriously have so much fun!
