### ISSUE TITLE
Do you have any children and why is your daughter named Phoenix?

### ISSUE THREAD

**Issue by sindresorhus** [stephenplusplus/ama#7]

**Comment by stephenplusplus** [comment]
I have two beautiful daughters. One is 2 1/2 (Phoenix) and the other is 3 months old (Berkley). Phoenix was just a name we found on a list and both loved instantly. You think naming modules is hard. Try a human.

**Comment by sindresorhus** [comment]
Where can I go and practice my human naming skills?
