### ISSUE TITLE
What if @passy gets bitten by a vampire?

### ISSUE THREAD

**Issue by sindresorhus** [stephenplusplus/ama#9]

**Comment by sindresorhus** [comment]
@passy

**Comment by stephenplusplus** [comment]
I love 8 people. Phoenix, Berkley, Jessica, mom, dad, Sindre, addy, and passy. I will do anything it takes, without exception, to make sure their lives are as enjoyable as they can be. But I guess if passy is a vampire, he's just screwed.

**Comment by passy** [comment]
:heartbeat: :heartbeat: :heartbeat:

**Comment by alrra** [comment]
> he's just screwed. 

... or he can just come live with me in Transylvania :jack_o_lantern:
